#!/bin/bash

if [ $# -eq 0 ]; then
  printf "No arguments. Use mtt -h to see available commands"
elif [ $1 = "--help" ] || [ $1 = "-h" ]; then
  printf "\n"
  tput bold; tput setaf 2; printf "##### MTT - Mattis Terminal Toolkit #####\n"; tput sgr0;
  printf "\n"
  printf "USAGE:\n"
  printf "\n"
  printf "  -h, --help        Shows this help\n"
  printf "  mtt test          Runs test script\n"
elif [ $1 = "test" ]; then
  "`dirname "$0"`"/mtt_scripts/test $2
else
  printf "Invalid arguments. Use mtt -h to see available commands"
fi
