#!/bin/bash

# scriptType; description; params...
declare -A scripts
scripts[sortcc]="stringScripts;Sorts the clipboard content.;";
scripts[base64]="stringScripts;Encode/decode base64 string.;string;";

scripts[portuse]="statScripts;Display which process is using specific port.;port"
scripts[topcpu]="statScripts;Displays top CPU usage."
scripts[topmem]="statScripts;Displays top MEM usage."

scripts[localkafka]="devScripts;Starts local kafka server."

if [ $# -eq 0 ]; then
  printf "No arguments. Use mtt -h to see available commands"
elif [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  printf "\n"
  tput bold; tput setaf 2; printf "##### MTT - Mattis Terminal Toolkit #####\n"; tput sgr0;
  printf "\n"
  printf "USAGE:\n"
  printf "\n"
  printf "  -h, --help           Shows this help\n\n"
  printf "String handling:\n"
  printf "  mtt sortcc           Sorts the clipboard content.\n"
  printf "  mtt base64 <string>  Encode/decode base64 string.\n "
  printf "\n"
  printf "Stats:\n" 
  printf "  mtt portuse <port>   Display which process is using specific port.\n"
  printf "  mtt topcpu           Displays top CPU usage.\n"
  printf "  mtt topmem           Displays top MEM usage.\n"
  printf "\n"
  printf "Dev tools:\n"  
  printf "  mtt localkafka       Starts local kafka server.\n"
else
  validScript=false
  for key in "${!scripts[@]}"; 
  do
    value=${scripts[$key]} 
    IFS=";" read -r -a arr <<< "${value}"
    #echo "$value"
    #echo "scriptType: ""${arr[0]}"""
    #echo "description: ""${arr[1]}"""
    #echo "param: ""${arr[2]}"""
    #echo "param2: ""${arr[3]}"""
    #echo "param3: ""${arr[4]}"""
    if [ "$1" = "$key" ]; then
      validScript=true
    fi
  done
  if [ "$validScript" = true ]; then
    "$(dirname "$0")"/mtt_scripts/"$1" "$2" "$3"
  else
    printf "Invalid arguments. Use mtt -h to see available commands"
  fi
fi

printf "\n"
