services:
  web:
    image: nginx:latest
    ports:
      - "9090:80"

  # Uncomment the following service to enable it
  # db:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example