#!/bin/bash


if [ $# -eq 0 ] || [ -z "$1" ]; then
  printf "No string specified. Usage: mtt base64 <string>"
else
  input=$1
  input="${input//-/+}"
  input="${input//_//}"
  echo $input
  echo " "

  tput setaf 6; printf "DECODED: \n"; tput sgr0;
  IFS='.' read -r -a array <<< "$input"
  for element in "${array[@]}"
  do
    # Fix padding
    len=$((${#element} % 4))
    if [ $len -eq 2 ]; then
      element="$element=="
    elif [ $len -eq 3 ]; then
      element="$element="
    fi

    echo -n "$element" | base64 --decode -w 0
    echo " "
    echo " "
  done
  tput setaf 6; printf "ENCODED: \n"; tput sgr0;
  echo -n "$input" | base64 -w 0
fi

echo " "

# Example encode from clipboard
# mtt base64 "$(mtt fromc)"
