#!/bin/bash


if [ $# -gt 0 ] && [ -n "$1" ]; then
  input=$1
elif [ ! -t 0 ]; then
  input=$(cat)
else
  printf "No string specified. Usage: mtt base64 <string>"
  echo " "
  exit 1
fi

{
  input=${input%$'\n'}
  echo $input
  echo " "

  inputFormatted="${input//-/+}"
  inputFormatted="${inputFormatted//_//}"

  tput setaf 6; printf "DECODED: \n"; tput sgr0;
  IFS='.' read -r -a array <<< "$inputFormatted"
  for element in "${array[@]}"
  do
    # Fix padding
    len=$((${#element} % 4))
    if [ $len -eq 2 ]; then
      element="$element=="
    elif [ $len -eq 3 ]; then
      element="$element="
    fi

    echo -n "$element" | base64 --decode -w 0
    echo " "
    echo " "
  done
  tput setaf 6; printf "ENCODED: \n"; tput sgr0;
  echo -n "$input" | base64 -w 0
}

echo " "

# Example encode from clipboard
# mtt base64 "$(mtt fromc)"
