#!/bin/bash

IN=$PATH
arrIN=(${IN//:/ })
mttPath="" 
for i in "${arrIN[@]}"; do
  if [[ $i == *"mtt"* ]]; then
    mttPath="$i"
  fi
done

if [ -z "$1" ]; then
  printf $mttPath"\n"
  printf "\n"
  ls -la $mttPath"/mtt_scripts"
  exit
fi

echo " "
tput setaf 7; cat $mttPath"/mtt_scripts/"$1; tput sgr0;
echo " "
