#!/bin/bash

mttPath="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [ -z "$1" ]; then
  printf "%s\n\n" "$mttPath"
  ls -la "$mttPath/mtt_scripts"
  exit
fi

echo " "
tput setaf 7; cat "$mttPath/mtt_scripts/$1"; tput sgr0;
echo " "
