#!/bin/bash

# Add to .zshrc: alias dcompose="cd /home/matti/projects_priv/mtt/resources && mtt compose"

# docker-compose.yaml on Gist: https://gist.github.com/mattinordstrom/520993d3fbdd9209c389beadd90867af

BLACK='\033[30m'
GREEN='\033[32m'
#RED='\033[31m'
YELLOW_BG='\033[43m'
YELLOW='\033[33m'
BOLD='\033[1m'
RESET='\033[0m'

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd $script_dir/../resources
yml_dir="$(pwd)"

file_to_check="docker-compose.yaml"
template_file="docker-compose_template.yaml"
if [ ! -f "$file_to_check" ]; then
  echo "$yml_dir/$file_to_check does not exist. Will create new from $template_file."
  cp "$template_file" "$file_to_check"
  chmod 600 $file_to_check
else
  echo "$yml_dir/$file_to_check exists. Using that!"
fi

echo " "

echo -e "${BLACK}${YELLOW_BG}SERVICES${RESET}"
echo -e "${BOLD}$(docker compose config --services | sort)${RESET}"
echo " "
echo -e "${BLACK}${YELLOW_BG}Running${RESET}"
echo -e "${BOLD}${GREEN}$(docker compose ps --status=running --format '{{.Service}}' | sort)${RESET}"


echo " "
echo "----------------------------"
echo " "


echo -e "${BOLD}${YELLOW} Run one service:${RESET}    $ docker compose up -d web"
echo -e "${BOLD}${YELLOW} Run all:${RESET}            $ docker compose up -d"
echo -e " "
echo -e "${BOLD}${YELLOW} Kill all:${RESET}           $ docker compose down"
echo -e "${BOLD}${YELLOW} Remove container:${RESET}   $ docker rm /redis"
echo -e " "
echo -e "${BOLD}${YELLOW} List containers:${RESET}    $ docker compose ps"
echo -e "${BOLD}${YELLOW} Show logs:${RESET}          $ docker compose logs web"
echo -e "${BOLD}${YELLOW} Rebuild:${RESET}            $ docker compose up -d --no-deps --build web"

