#!/bin/bash

# Add to .zshrc: alias dcompose="cd /home/matti/projects_priv/mtt/resources && mtt compose"

# docker-compose.yaml on Gist: https://gist.github.com/mattinordstrom/520993d3fbdd9209c389beadd90867af

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd $script_dir/../resources
yml_dir="$(pwd)"

echo " "
echo "Changed dir to $yml_dir"
echo " "

file_to_check="docker-compose.yaml"
template_file="docker-compose_template.yaml"
if [ ! -f "$file_to_check" ]; then
  echo "$yml_dir/$file_to_check does not exist. Will create new from $template_file."
  cp "$template_file" "$file_to_check"
else
  echo "$yml_dir/$file_to_check exists. Using that!"
fi


echo " "
echo "----------------------------"
echo " "
echo "Services in yaml: "

tput bold; tput setaf 6;
docker compose config --services
tput sgr0;

echo " "
echo "----------------------------"
echo " "

tput setaf 3
echo "Run one service:    $ sudo docker compose up web"
echo "Run all (detached): $ sudo docker compose up -d"
echo "List containers:    $ sudo docker compose ps"
echo "Kill all:           $ sudo docker compose down"
tput sgr0;
