#!/bin/bash

# gsettings set org.gnome.desktop.session idle-delay 3600

seconds=$1*60

start="$(( $(date '+%s') + $seconds))"
while [ $start -ge $(date +%s) ]; do
    time="$(( $start - $(date +%s) ))"
    printf '%s\r' "$(date -u -d "@$time" +%H:%M:%S)"
    sleep 0.1
done

printf '################ DONE! ################'

# gsettings set org.gnome.desktop.session idle-delay 240
