#!/bin/bash

screenblankdelay=$(gsettings get org.gnome.desktop.session idle-delay)
screenblankdelay=$(echo $screenblankdelay | sed 's/uint32 //') 
echo "Initial screen blank delay: $screenblankdelay"
echo " "

#gsettings set org.gnome.desktop.session idle-delay 3600

seconds="$(echo "$1 * 60" | bc -l)"
seconds=$(LC_ALL=C printf '%.0f' "$seconds") #float to int

start="$(( $(date '+%s') + $seconds))"
while [ $start -ge $(date +%s) ]; do
    time="$(( $start - $(date +%s) ))"
    printf '%s\r' "$(date -u -d "@$time" +%H:%M:%S)"
    sleep 0.1
done

printf "(Setting screen blank delay to $screenblankdelay)"
gsettings set org.gnome.desktop.session idle-delay $screenblankdelay

echo " "
printf '################ DONE! ################'