#!/bin/bash

screenblankdelay=$(gsettings get org.gnome.desktop.session idle-delay)
screenblankdelay=$(echo $screenblankdelay | sed 's/uint32 //') 
echo "Initial screen blank delay: $screenblankdelay"
echo " "

echo "!!! Setting screen blank delay temporarily to 3600 !!!"
echo "gsettings set org.gnome.desktop.session idle-delay 3600"
echo " "
gsettings set org.gnome.desktop.session idle-delay 3600

seconds="$(echo "$1 * 60" | bc -l)"
seconds=$(LC_ALL=C printf '%.0f' "$seconds") #float to int

start="$(( $(date '+%s') + $seconds))"
while [ $start -ge $(date +%s) ]; do
    time="$(( $start - $(date +%s) ))"
    printf '%s\r' "$(date -u -d "@$time" +%H:%M:%S)"
    sleep 0.1
done

echo "Setting screen blank delay back to $screenblankdelay"
echo "gsettings set org.gnome.desktop.session idle-delay $screenblankdelay"
gsettings set org.gnome.desktop.session idle-delay $screenblankdelay

echo " "
echo '################ DONE! ################'