#!/bin/bash

if [ -z "$2" ]; then
  find ~ -name "$1"
else
  sudo find "$2" -name "$1"
fi


# Example find pdf containing Test in filename:
# mtt find "*.pdf" | grep -i test

# Exampel find files with filename starting with "image" in the Downloads directory:
# mtt find "image*" ~/Downloads
