#!/bin/bash

IN=$PATH
arrIN=(${IN//:/ })
mttPath="" 
for i in "${arrIN[@]}"; do
  if [[ $i == *"mtt"* ]]; then
    mttPath="$i"
  fi
done

tstamp=`date +%Y-%m-%d-%H-%M-%S`

mkdir -p ~/Desktop/go_scratches

cp -r $mttPath/resources/SCRATCH_TEMPLATE_GO ~/Desktop/go_scratches/scratch-go-$tstamp

code ~/Desktop/go_scratches/scratch-go-$tstamp