#!/bin/bash


# Locate Kafka directory in ~
KAFKA_DIR=$(ls ~ | grep -E "^kafka_[0-9]+\.[0-9]+.*" | head -1)
KAFKA_DIR=~/$KAFKA_DIR
KAFKA_KRAFT_CONFIG=$KAFKA_DIR/config/kraft/server.properties


#Remove old logs and setup storage
rm -rf /tmp/kafka-logs/*
rm -rf /tmp/kraft-combined-logs/*
randomid=$($KAFKA_DIR/bin/kafka-storage.sh random-uuid)
$KAFKA_DIR/bin/kafka-storage.sh format -t $randomid -c $KAFKA_KRAFT_CONFIG


echo "Kafka server starting..."
$KAFKA_DIR/bin/kafka-server-start.sh $KAFKA_KRAFT_CONFIG
