#!/bin/bash

IN=$PATH
arrIN=(${IN//:/ })
mttPath="" 
for i in "${arrIN[@]}"; do
  if [[ $i == *"mtt"* ]]; then
    mttPath="$i"
  fi
done

tstamp=`date +%Y-%m-%d-%H-%M-%S`

mkdir -p ~/Desktop/py_scratches

cp $mttPath/resources/SCRATCH_TEMPLATE.py ~/Desktop/py_scratches/scratch-$tstamp.py

code ~/Desktop/py_scratches/scratch-$tstamp.py