#!/bin/bash

xclip -selection clipboard -o | sed "s/$1.*$2/$1$3$2/g"

# Example double qoutes in content (use single qoutes in params!)
#
#   <div class="menu menuitem_start" onclick=...
#   <div class="menu menuitem_faq" onclick=...
#
# mtt replaceccb 'class=\"menu ' '\" onclick' 'menuitem_same'
