#!/bin/bash

if [ $# -eq 0 ] || [ -z "$1" ]; then
  printf "Current timestamp (now): "; echo $(date +%s)
else
  if [[ $1 == *"-"* ]]; then
    printf "Timestamp ($1): "; date -d "$1" +%s
    printf "Timestamp ($1) UTC+1: "; date -d "$1 UTC+1" +%s
    printf "Timestamp ($1) UTC+2: "; date -d "$1 UTC+2" +%s
  else
    printf "Timestamp ($1) to date: "; echo "$1" | awk '{print strftime("%c", $0)}'
  fi
fi


