#!/bin/bash

input=$1

if [ $# -eq 0 ] || [ -z "$1" ]; then
  printf "Current timestamp (now): "; echo "$(date +%s)"
else
  if [[ $input == *"-"* ]]; then
    printf "Timestamp ($1): "; date -d "$1" +%s
    printf "Timestamp ($1) UTC+1: "; date -d "$1 UTC+1" +%s
    printf "Timestamp ($1) UTC+2: "; date -d "$1 UTC+2" +%s
  else
    formattedInput=${input:0:10}
    printf "Timestamp ($formattedInput) to date: "; echo $formattedInput | awk '{print strftime("%c", $0)}'
  fi
fi


