#!/bin/bash

if [ -z "$1" ]; then
  xclip -selection clipboard
else
  xclip -selection clipboard -i < "$1"
fi

# Example file content to clipboard:
# mtt toc file.txt

# Example echo string to clipboard:
# echo "test" | mtt toc

# Example save current path to clipboard:
# echo $(pwd) | mtt toc
