#!/bin/bash

YELLOW="\e[33m%s\e[0m"

printf "\n"

printf $YELLOW " PHP: "; php -r 'echo rtrim(phpversion());'
printf "\n"
printf $YELLOW " XDEBUG: "; php -r 'echo phpversion("xdebug");'

printf "\n"
printf "\n"

printf $YELLOW " NODE: "; node -v
printf $YELLOW " NPM: "; npm -v

printf "\n"

printf $YELLOW " JAVA: "; java -version 2>&1 | grep version

printf "\n"

printf $YELLOW " GO: "; go version

printf "\n"

printf $YELLOW " PYTHON: "; python3 -V
printf $YELLOW " PIP: "; pip3 --version

printf "\n"
