#!/bin/bash

weekDaysArray=( "Monday" "Tuesday" "Wednesday" "Thursday" "Friday" "Saturday" "Sunday" )
currentDayIdx=$(date +%u)
currentDayName=${weekDaysArray[$currentDayIdx-1]}

echo " "
tput setaf 3; echo "-------------------------------------------------------"; tput sgr0;
echo " "

tput bold; tput setaf 6; echo "   "$currentDayName, $(date +%d) $(date +%B) $(date +'%Y (%H:%M:%S)'); tput sgr0; tput sgr0;
currentWeek=$(date +%V)
tput setaf 6; echo "   Current week: $currentWeek"; tput sgr0;

echo " "
echo " "
weekOutput=''
for i in ${!weekDaysArray[@]}; do
  dayOneIdx="$(($i + 1))"
  
  if [ "$dayOneIdx" -ge "$currentDayIdx" ]; then
    if [ "$dayOneIdx" -eq "$currentDayIdx" ]; then
      weekOutput=$weekOutput"->|"${weekDaysArray[$i]}"|"$(date -d-${weekDaysArray[$i]} +%Y-%m-%d)"\n"
    else
      weekOutput=$weekOutput"|"${weekDaysArray[$i]}"|"$(date -d-${weekDaysArray[$i]} +%Y-%m-%d)"\n"
    fi
  else
    weekOutput=$weekOutput"|"${weekDaysArray[$i]}"|"$(date -dlast-${weekDaysArray[$i]} +%Y-%m-%d)"\n"
  fi
done

weekOutput=$(echo -e $weekOutput) #interpret slash n as newline
column -t -s "|" <<< $weekOutput #print week in column format

echo " "
tput setaf 3; echo "-------------------------------------------------------"; tput sgr0;
echo " "
